server:
    port: 8080

paths:
    targetDir: E:\target
    maven:  E:\dev\tools\apache-maven-3.3.3\bin\mvn.cmd
    gradle: E:\dev\tools\apache-maven-3.3.3\bin\mvn.cmd
    sbt:  E:\dev\tools\apache-maven-3.3.3\bin\mvn.cmd